### PR TITLE
Update fontawesome to 4.5.0

### PR DESCRIPTION
**Pull request by mikmikmik**

### CODE REVIEW

**Comment by rstacruz** [comment]
I see you figured out how to do an update... how'd you figure it out? :)

**Comment by rstacruz** [comment]
released as 0.9.0. thanks!

**Comment by mikmikmik** [comment]
Hey, thanks for your work, I'm not used to github I hope I'm not doing things awkwardly... I managed to update font-awesome.json by copy-pasting from https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss / editing with sublime-text and then make -B :)

**Comment by rstacruz** [comment]
ah, neat! that works too. you're doing great!

**Comment by mikmikmik** [comment]
Should have I change the version number in my files ? Thanks.

**Comment by rstacruz** [comment]
heheh, next time don't—leave that for the package maintainers to do :)

**Comment by mikmikmik** [comment]
hehe ok

**Pull request merged**
